Update appmesh-baseline.yml
```
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Done installing documentation for bundler after 3 seconds
38 gems installed
+ gem update --system
ERROR:  Error installing rubygems-update:
        There are no versions of rubygems-update (= 3.4.21) compatible with your Ruby & RubyGems
        rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
Updating rubygems-update
```

Commenting out the `gem update --system` as it causes bootstrap failure, which causes a 5XX behaviour from LB